"""
Django settings for library_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mo=dliprbo8!0crmgi4rc6*mw%4r8im9bb*0!n3tpu_jz@z&)v'

# Режим отладки: включает детальные ошибки и автоматическую перезагрузку.
DEBUG = True
# Пустой список разрешает только localhost при DEBUG=True.
ALLOWED_HOSTS = []


# ==============================================================================
# ПОДКЛЮЧЕННЫЕ ПРИЛОЖЕНИЯ
# ==============================================================================
# Порядок имеет значение: приложения, перечисленные первыми, имеют приоритет при разрешении конфликтов шаблонов/статики.
INSTALLED_APPS = [
    # Междоменная политика безопасности (CORS) — нужна для запросов с React-фронтенда
    'corsheaders',
    # Стандартные приложения Django
    'django.contrib.admin',        # Админка
    'django.contrib.auth',         # Аутентификация пользователей
    'django.contrib.contenttypes', # Типы контента (используется auth и другими)
    'django.contrib.sessions',     # Управление сессиями (для staff login/logout)
    'django.contrib.messages',     # Сообщения пользователю (например, об успешной операции)
    'django.contrib.staticfiles',  # Работа со статическими файлами
    # Сторонние библиотеки
    'rest_framework',              # Django REST Framework — для API
    'django_extensions',           # Утилиты для разработки (например, shell_plus)
    # Кастомное приложение проекта — содержит модели, views и логику библиотечной системы
    'library',
]

# Последовательность обработки запросов и ответов.
MIDDLEWARE = [
    # Обработка CORS-заголовков — должна быть первой среди пользовательских middleware
    'corsheaders.middleware.CorsMiddleware',
    
    # Защита от распространённых уязвимостей
    'django.middleware.security.SecurityMiddleware',
    
    # Управление сессиями
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Общие функции: обработка слэшей, редиректы
    'django.middleware.common.CommonMiddleware',
    
    # Защита от CSRF-атак
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # Аутентификация пользователей (для админки)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Сообщения пользователю (например, уведомления о штрафах)
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Защита от clickjacking (встраивание сайта в iframe)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'library_backend.urls' # Главный файл маршрутов проекта

# Используется только для админки Django и возможных HTML-страниц (все остальное — REST API).
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Дополнительные директории шаблонов (не используются в текущем проекте)
        'APP_DIRS': True,  # Автоматический поиск шаблонов в папке templates/ каждого приложения
        'OPTIONS': {
            'context_processors': [
                # Делает request доступным в шаблонах
                'django.template.context_processors.request',
                # Делает user и auth-данные доступными в шаблонах (для админки)
                'django.contrib.auth.context_processors.auth',
                # Делает messages доступными в шаблонах
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Используется PostgreSQL согласно ТЗ проекта.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'library_db',      # название базы
        'USER': 'postgres',        # пользователь PostgreSQL
        'PASSWORD': '',            # пароль от него
        'HOST': 'localhost',       # адрес (или имя контейнера)
        'PORT': '5432',            # порт PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},  # Не похож на имя/логин
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},             # Минимальная длина
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},            # Не из списка популярных
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},           # Не только цифры
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Проект использует английский интерфейс и UTC-время для единообразия хранения даты/времени в БД.
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'              # Все datetime хранятся в UTC (USE_TZ=True)
USE_I18N = True                # Включена поддержка переводов (для админки)
USE_TZ = True                  # Используются timezone-aware datetime

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Разрешает запросы с фронтенда на http://localhost:5173 (Vite dev server).
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Порт по умолчанию для React + Vite
]

CORS_ALLOW_CREDENTIALS = True

# DRF по умолчанию включает SessionAuthentication, которая требует CSRF для
# unsafe-запросов, если в браузере уже есть session (например, после входа в /admin).
# Мы используем собственную сессионную авторизацию через request.session['staff_id'],
# поэтому отключаем DRF-auth, чтобы API работал из фронтенда без CSRF-токена.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}
